# Generated by Django 4.2 on 2025-09-10 14:29

from ..models.announcement import Announcement
import cis.storage_backend
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields
import multiselectfield.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text')),
                ('applies_to', multiselectfield.db.fields.MultiSelectField(choices=[('applicant', 'Applicant'), ('ce', 'RMU Administrator'), ('district_admin', 'District Admin'), ('faculty', 'Faculty'), ('highschool_admin', 'High School Admin'), ('instructor', 'Instructor'), ('student', 'Student'), ('speaker', 'Speaker')], max_length=300)),
                ('display_weight', models.SmallIntegerField(default=0)),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='BulkMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('message', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Text')),
                ('send_summary', models.JSONField(default=dict)),
                ('datasource', models.JSONField(default=dict)),
                ('meta', models.JSONField(default=dict)),
                ('media', models.FileField(blank=True, null=True, storage=cis.storage_backend.PrivateMediaStorage(), upload_to=cis.utils.bulk_message_media_upload_path)),
                ('createdon', models.DateTimeField(auto_now_add=True)),
                ('send_on_after', models.DateTimeField(blank=True, null=True)),
                ('send_until', models.DateTimeField(blank=True, null=True)),
                ('cron', models.CharField(max_length=100)),
                ('status', models.CharField(blank=True, choices=[('draft', 'Draft'), ('ready_to_send', 'Ready to Send'), ('sent', 'Sent')], default='draft', max_length=30, null=True)),
                ('createdby', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BulkMessageRecipient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(blank=True, max_length=128, null=True)),
                ('last_name', models.CharField(blank=True, max_length=128, null=True)),
                ('meta', models.JSONField(default=dict)),
                ('status', models.CharField(blank=True, choices=[('', ''), ('pending', 'Pending'), ('failed', 'Failed'), ('sent', 'Sent')], default='', max_length=30, null=True)),
                ('bulk_message', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='announcement.bulkmessage')),
            ],
        ),
        migrations.CreateModel(
            name='BulkMessageLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_completed_on', models.DateTimeField(blank=True, null=True)),
                ('run_started_on', models.DateTimeField(blank=True, null=True)),
                ('run_scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('meta', models.JSONField(default=dict)),
                ('log_file', models.FileField(blank=True, storage=cis.storage_backend.PrivateMediaStorage(), upload_to=cis.utils.bulk_message_log_upload_path)),
                ('bulk_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='announcement.bulkmessage')),
            ],
        ),
    ]
