# Generated by Django 5.2.15 on 2026-06-15 19:33

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='applies_to',
            field=multiselectfield.db.fields.MultiSelectField(max_length=300),
        ),
    ]
