# Generated by Django 2.2.5 on 2019-11-11 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0002_auto_20191028_1050'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImportantLink',
        ),
    ]
