# Generated by Django 2.2.7 on 2019-11-23 19:20

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0003_delete_importantlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='applies_to',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Students', 'Students'), ('High School Administrators', 'High School Administrators'), ('Instructors', 'Instructors')], max_length=30),
        ),
    ]
