# Generated by Django 3.0.5 on 2020-04-28 10:02

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0008_auto_20191124_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='applies_to',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Students', 'Students'), ('High School Administrators', 'High School Administrators'), ('Instructors', 'Instructors'), ('Faculty', 'Faculty')], max_length=300),
        ),
        migrations.AlterUniqueTogether(
            name='announcement',
            unique_together=set(),
        ),
    ]
