# Generated by Django 3.2 on 2023-07-12 14:53

import announcement.models.announcement
import cis.storage_backend
import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('announcement', '0011_alter_announcement_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('message', ckeditor.fields.RichTextField(blank=True)),
                ('send_summary', models.JSONField(default=dict)),
                ('datasource', models.JSONField(default=dict)),
                ('meta', models.JSONField(default=dict)),
                ('media', models.FileField(blank=True, null=True, storage=cis.storage_backend.PrivateMediaStorage(), upload_to=announcement.models.announcement.bulk_message_media_upload_path)),
                ('createdon', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, choices=[('draft', 'Draft'), ('ready_to_send', 'Ready to Send')], default='draft', max_length=30, null=True)),
                ('createdby', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
