# Generated by Django 3.2 on 2023-07-13 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0012_bulkmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkmessage',
            name='send_on_after',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bulkmessage',
            name='status',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('ready_to_send', 'Ready to Send'), ('sent', 'Sent')], default='draft', max_length=30, null=True),
        ),
    ]
