# Generated by Django 3.2 on 2023-07-13 20:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0013_auto_20230712_1921'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkMessageRecipient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(blank=True, max_length=128, null=True)),
                ('last_name', models.CharField(blank=True, max_length=128, null=True)),
                ('meta', models.JSONField(default=dict)),
                ('status', models.CharField(blank=True, choices=[('', ''), ('pending', 'Pending'), ('sent', 'Sent')], default='', max_length=30, null=True)),
                ('bulk_message', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='announcement.bulkmessage')),
            ],
        ),
    ]
