# Generated by Django 3.2 on 2023-07-23 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0014_bulkmessagerecipient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkmessagerecipient',
            name='status',
            field=models.CharField(blank=True, choices=[('', ''), ('pending', 'Pending'), ('failed', 'Failed'), ('sent', 'Sent')], default='', max_length=30, null=True),
        ),
    ]
