# Generated by Django 4.2 on 2024-04-04 01:22

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0015_alter_bulkmessagerecipient_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkmessage',
            name='cron',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bulkmessage',
            name='send_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='bulkmessage',
            name='message',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True),
        ),
    ]
