# Generated by Django 4.2 on 2024-04-07 14:23

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0018_bulkmessagelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='applies_to',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('applicant', 'Applicant'), ('ce', 'CEP Staff'), ('district_admin', 'District Admin'), ('faculty', 'Faculty'), ('highschool_admin', 'High School Admin'), ('tech_center_staff', 'UMA Center Staff'), ('instructor', 'Instructor'), ('student', 'Student'), ('speaker', 'Speaker')], max_length=300),
        ),
    ]
